### ISSUE TITLE
Zpanel 10.1.1 Cosmetic Bug

### ISSUE THREAD

**Issue by davetom13** [zpanel/zpanelx#121]
Update page states:

"You appear to be running a BETA release, unless you are testing or developing we recommend you download and use the latest stable release (10.1.0)."

Has no effect on system that can be seen.

**Comment by allebb** [comment]
Run a forced daemon run and this will reset, this is due to the current version being cached on your server :)

/close

**Comment by allebb** [comment]
Closing as this is not an issue as per my statement above.

**Comment by davetom13** [comment]
no problem, just came across that when i was checking everything out. Looks like daemon cleared it up. Thanks Bobby!
