### ISSUE TITLE
Cron & Named Permissions

### ISSUE THREAD

**Issue by stokes84** [zpanel/zpanelx#125]
Looks like two slight bugs are lingering that are present on CentOS 6.4 x86_64 and other CentOS versions (as stated in forum fixes).

Fresh install on updated CentOS x86_64 renders cronjobs unable to be created and dns logs unable to be read. Also the "Set Permissions" button does not remedy. 

<p align="center">
  <img src="http://i.imgur.com/saj377I.png" alt="Log file is not Readable">
</p>

<p align="center">
  <img src="http://i.imgur.com/l1NbWqm.png" alt="System Cron file could not be created">
</p>

<strong>Original DNS Log Fix:</strong> [Resolved @ Support Forum](http://forums.zpanelcp.com/Thread-CentOs-6-3-DNS-Config-Log-file-is-not-Readable?pid=39961#pid39961) 

<strong>Original Cron Fix:</strong> [Resolved @ Support Forum](http://forums.zpanelcp.com/Thread-SOLVED-system-cron-file-could-not-be-created)

<br>

<strong>New DNS Fix:</strong>  `chmod 751 /var/named | chmod 771 /var/named/data` 
- Changing permissions from 750 to 751 on named and also changing permissions from 770 to 771 on data folder allows zpanel to execute named.run
- Possible underlying ownership error since this is requiring public execution permissions to get log access but is this even a security risk?
- Only tested exact permissions needed to read log file, didn't generate errors to "Clear" or "View".

<br>

<strong>New Cron Fix:</strong>  `chmod 744 /var/spool/cron` 
- changing permissions from 644 to 744 allows zpanel to write cronjobs

<br>

Could these fixes be included in etc/build/prepare.sh like so?

<dl>
  <dt>Example</dt>
</dl>

```
echo "Setting permissions.."
chmod -R 777 /etc/zpanel/
chmod -R 777 /var/zpanel/
chmod 751 /var/named
chmod 771 /var/named/data
chmod 744 /var/spool/cron
echo "Complete!"
```

**Comment by TheNigelist** [comment]
Wouldn't a `chmod -R 751 /var/named/` be better??

**Comment by stokes84** [comment]
~~For sure~~ I mean it'd be simpler no doubt, was keeping the permissions tight. Only bumped exactly what was needed for access as opposed to a blanket solution.

**Comment by allebb** [comment]
Chris is right, we should ideally only be setting permission where we need to! Cheers for the PR Chris!

**Comment by stokes84** [comment]
Thanks Bobby! Tossed the pull request in there attached to the Webalizer Module fix. Was originally just opening up for debate but looks good to go. Haven't generated any errors to tinker with but log viewing and counting is working fine.

**Comment by bitridge** [comment]
you guys are awesome, I was the first one to ask this issue on zpanel forum but that forum is down now, so you are a lifesaver.

**Comment by Ron-e** [comment]
Just for your knowledge: Zpanel is dead after the acquisition by Hostwinds and the voluntary staff have started an zPanel fork called Sentora and they have there own forum where they also give zPanel support..

http://sentora.org/
http://forums.sentora.org/

**Comment by bitridge** [comment]
Hi Ron,

thanks, is Sentora also similar to Zpanel and same features? hows the security.

thanks,

**Comment by Ron-e** [comment]
Yes, it can be seen like zPanel 10.1.2 or 10.2.0 like TGates (also from old zPanel team) said on the Sentora forum..
http://forums.sentora.org/showthread.php?tid=49&pid=262#pid262
There even will be an update script from zPanel 10.1.1 to Sentora 1.0.0 which is currently in RC stage.
