### ISSUE TITLE
postmaster@domain.tld and abuse@domain.tld

### ISSUE THREAD

**Issue by jcerdan** [zpanel/zpanelx#130]
Those 2 e-mails should automatically be added for every domain active in ZPanel. They should not be deleted by any customer.

**Comment by allebb** [comment]
Really?

Do you have thoughts on the following then?....

1) What should happen when the ZPanel hosting account package type does not
allow any mailboxes for the user's package type?

2) What about In the event that the user has configured emails to be hosted
on a different server? (by adding customer MX records in the DNS manager?)

**Comment by jcerdan** [comment]
oops...you're right. 

Actually, in my config those situations are not possible, so I didn't thought about this evident situations.
I'll try to do this somehow in my particular infrastructure.

Sorry for bothering you. Anyway, thanks for waking me up.

**Comment by allebb** [comment]
lol, no problem buddy... I just thought I'd raise those situations though
:) - In an ideal world it would be great to do, as you've said but in
reality with the number of users using ZPanel and in so many different ways
etc. this isn't really 100% possible :)

Cheers,
Bobby

**Comment by allebb** [comment]
Closing 'issue' as no further updates are required as per the discussion above.
