### ISSUE TITLE
Apache access log rotation

### ISSUE THREAD

**Issue by jcerdan** [zpanel/zpanelx#131]
It should be interesting to have Apache log rotation on ZPanel. Is that possible?

**Comment by stokes84** [comment]
This is more of a feature request than an "Issue". I know in CentOS, by default log rotations are weekly and 4 weeks of previous logs are kept. I can't recall Ubuntu's default log rotations. Unfortunately with any panel you won't cover all bases so you'll still have to administer your server from time to time. This is an easy one though just look into the [logrotate](http://linuxcommand.org/man_pages/logrotate8.html) package. It's well documented all over the interwebz in regards to install and setup.

**Comment by jacobgelling** [comment]
@stokes84 :+1: 

I think this should be the admin's job rather than ZPanels. I've got mine rotating every couple days and then backing up to another server.

**Comment by jcerdan** [comment]
Well, Apache logs are used for stats. It should be interesting to know how long are those logs processed so that log rotation won't affect the stats processing (awstats module installed).

**Comment by allebb** [comment]
Yep agree with @jacobg830 this is the job of the server admin as so many people I'm sure would have preferred configurations (rotation times etc.) :)

@jcerdan Good point, but bandwidth generation is aggregated from a separate 'access' file and then truncated automatically after generation :) - So as long as the log rotation is NOT configured for the bandwidth.access.log file then should be good :)
