### ISSUE TITLE
all (new) domains pointing to zpanelcp

### ISSUE THREAD

**Issue by fezzie** [zpanel/zpanelx#136]
when a client add a new domain, this point to the zpanelcp and not to the index.html in the folder that has been made.

os: linux ubuntu 
zpanel: 10.1.1

**Comment by dansanti** [comment]
HI! try forcing a update from here http://your-server/?module=apache_admin , well this working to me after adding too  on global vhosting entry this:</VirtualHost> 
<VirtualHost *:80> 
ServerAlias mail.\* 
DocumentRoot "/etc/zpanel/panel/etc/apps/webmail/"

</VirtualHost> 
<VirtualHost *:80> 
ServerAlias panel.\* 
DocumentRoot "/etc/zpanel/panel/"

click on force update and save

**Comment by dansanti** [comment]
*_That entry :
< /VirtualHost > 
< VirtualHost *:80 > 
ServerAlias mail._ 
DocumentRoot "/etc/zpanel/panel/etc/apps/webmail/"

< /VirtualHost > 
< VirtualHost _:80 > 
ServerAlias panel._ 
DocumentRoot "/etc/zpanel/panel/"

**Comment by TheNigelist** [comment]
Have you setup the DNS settings?

This would be one of the only reasons why a domain would show your login page.

**Comment by fezzie** [comment]
the dns setup will be done automaticaly by zpanel after install, right?
This issue i never had in 10.1.0 i never touched the dns configs, and it works always good for me.

thanks guys

**Comment by TheNigelist** [comment]
At your registrar?

The DNS does not get done automatically by ZPanel, it never has.

The DNS module changed in 10.1.1.

**Comment by fezzie** [comment]
in my zpanel dns registrar it gave me: Your DNS zone has been loaded without errors.
i think this is not the problem

**Comment by TheNigelist** [comment]
![facepalm](https://f.cloud.github.com/assets/1205726/2366850/a120427c-a725-11e3-9ac6-969fdc10db4e.png)
Your domain registrar dude.

Have you also checked if bind is working and that your zone records haven't changed?

**Comment by fezzie** [comment]
the record zone havent changed! how to look if bind is working well?

**Comment by TheNigelist** [comment]
[Here](http://lmgtfy.com/?q=how+to+check+if+bind+working)

**Comment by stokes84** [comment]
Lol, ya this kinda stuff and a lot of "issues" I see on here lately belong on the forums. That way they can indexed, searched, and 47 people don't get an email for every piece of correspondence between people.

**Comment by allebb** [comment]
Closing this 'issue' as it does not match the criteria of being a bug ;)
