### ISSUE TITLE
Error after update. Connection failed.

### ISSUE THREAD

**Issue by RubensSalles** [zpanel/zpanelx#140]
Hello I am installing zpanel. 
Usually installed by following a tutorial, cconsegui access to admin. 
I had already created my domains and database. 
When I noticed that he was requesting an update. 
I updated and I can not access SSH, not with the admin server ip and even with the domain.

**Comment by jacobgelling** [comment]
If you want help fixing it then you should post this on the forums. It's mainly just the developers here on GitHub.

**Comment by allebb** [comment]
Closing issue, this is a support issue and not a bug, please follow @jacobg830 advice and use the forums at: http://forums.zpanelcp.com for help and support.
