### ISSUE TITLE
DNS TXT record, on paste and save, is not the same result

### ISSUE THREAD

**Issue by didyouexpectthat** [zpanel/zpanelx#143]
I have DNS hosted using zpanel
On one of my records, I created google._domainkey for my TXT record for DKIM.

I pasted in the following into the target:
v=DKIM1; k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCLZXkUVC/1VOwTHw00xQLDK+qlkRlVhr/4avYQfOlf275P9dbCizngpODCrdg76UrjuNlIuX0j1Ish5e1zxvopDKPCL4K/z/mLVuGAQTjrRt4UZ9EAT4NdN9/xDEM0ff/W+dTc5XI2lvS+ksBKNvpZ/jMC4FRvBj9xKH2AZU5YmwID[1234]
Where [1234] is the last 4 digits of my key.

When I save the entry, I receive this in the GUI and in the SQL database:

v=dkim1; k=rsa; p=migfma0gcsqgsib3dqebaquaa4gnadcbiqkbgqclzxkuvc/1vowthw00xqldk+qlkrlvhr/4avyqfolf275p9dbcizngpodcrdg76urjunliux0j1ish5e1zxvopdkpcl4k/z/mlvugaqtjrrt4uz9eat4ndn9/xdem0ff/w+dtc5xi2lvs+ksbknvpz/jmc4frvbj9xkh2azu5ymwid[1234]

TXT codycook._domainkey.codycook.us 17 min  v=dkim1; k=rsa; p=migfma0gcsqgsib3dqebaquaa4gnadcbiqkbgqclzxkuvc/1vowthw00xqldk+qlkrlvhr/4avyqfolf275p9dbcizngpodcrdg76urjunliux0j1ish5e1zxvopdkpcl4k/z/mlvugaqtjrrt4uz9eat4ndn9/xdem0ff/w+dtc5xi2lvs+ksbknvpz/jmc4frvbj9xkh2azu5ymwid[1234]

Also, this violates RFC 4871, 3.2 "Tags MUST be interpreted in a case-sensitive manner. Values MUST be processed as case sensitive unless the specific tag description of semantics specifies case insensitivity."

As this is clearly a RSA key, it should be case-sensitive.
zpanel fails to keep case when applying DNS settings.

As a workaround, I've tried to edit directly in database. I still cannot send e-mail though.

**Comment by stokes84** [comment]
Line 1001 of `modules/dns_manager/code/controller.ext.php` looks to be the culprit.

`$data = strtolower($data);`

Looks like line 1084 is where you'll see it being passed to the `CleanRecord` function. This can be fixed, good catch.

**Comment by ghost** [comment]
Yes dns should be case sensitive and this need to be fixed
Me.b

**Comment by allebb** [comment]
I'll implement a fix tomorrow... I'll add a conditional for TXT records as CNAME targets do look better as lowercase though!

**Comment by didyouexpectthat** [comment]
I agree that CNAME targets look better as lowercase... However, when reading RFC 4343, DNS Case Insensitivity Clarification, section 4,  I see that 'case MUST be preserved on output and preserved when convenient on input.' -- does this mean that case should not be modified in general when applying to DNS? 

https://www.ietf.org/rfc/rfc4343.txt

Is the keyword "when convenient" the reason to force CNAME in lowercase?

**Comment by allebb** [comment]
I agree with what you are saying, what I mean't was and am saying is that i'm saying that i'll add a conditional sting to lower for CNAME records only! TXT record values will therefore remain untouched (unformatted) thus will ensure that it abides to the RFC.

**Comment by didyouexpectthat** [comment]
I see. Thanks for the clarification. :+1: 
This will help me out tremendously as I have a lot of domains with TXT records. Thanks again.

**Comment by allebb** [comment]
This has now been fixed and latest version can be seen in this commit: https://github.com/zpanel/zpanelx/commit/6e51c5eaceab25b0f833967a74304607e7e4d2fb
