### ISSUE TITLE
Backup doesn't contain emails

### ISSUE THREAD

**Issue by b-boom** [zpanel/zpanelx#146]
The zpanelx backup from the default backup funciton only contains the public_html folder and the MySQL databases.

It would be nice if a backup also contains emailaccounts (and their content). Users maybe want to backup their emal.

**Comment by ghost** [comment]
This is not a bug. Zipping daily emails is totally crazy. 

Email require different backup mode than the one currently used. Imagine you have big mailboxes and holding 7 days copy!

I expect backup mainly over web & SQL and might later think about feature that would allow only Mysql daily while websites less frequently. BUT email it's far far more complicated sir.

M B

**Comment by allebb** [comment]
The backup of emails is something that the server administrator should be doing as part of their 'main' server backups and obviously exporting out to a remote server.
