### ISSUE TITLE
Module Admin View

### ISSUE THREAD

**Issue by TheNigelist** [zpanel/zpanelx#159]
The module admin doesn't display properly when you add more modules to it.

This issue was reported at the old bugs site but was never fixed.

![server_admin_view](https://f.cloud.github.com/assets/1205726/2444392/eaceb0a0-ae52-11e3-820c-48637efac672.png)

**Comment by stokes84** [comment]
Check out #155

**Comment by g0ddish** [comment]
This guy was born with some extra chromosomes ignore this issue.

**Comment by TheNigelist** [comment]
I'm running the latest code @stokes84.

I'll double check.

**Comment by TheNigelist** [comment]
@stokes84 I didn't copy over the style folder because I run a custom master.ztml and didn't want it to change.

Thanks man all sorted I'll close this issue now.

**Comment by TheNigelist** [comment]
I missed a commit.
