### ISSUE TITLE
can't set  domain containing www.com 

### ISSUE THREAD

**Issue by peterwhitin** [zpanel/zpanelx#164]
Hey ,

I was trying to sent a domain magazineswww.com  , but it was not active ,

please let me know hot do i set this domain in zpanal cp 

pls help us

**Comment by allebb** [comment]
Please log your support issue via the forums, Github should be for 'bugs' only really, cheers

**Comment by peterwhitin** [comment]
Thank you,

but i felt it is a bug , because i could not add this doamin "magazineswww.com" to my account in zpanel

**Comment by jacobgelling** [comment]
:+1: I can replicate this bug. No domain containing "www" in it can be added :confused:

**Comment by ghost** [comment]
BUG confirmed here as I got error too

for testwww.zzz

"Please remove 'www'. The 'www' will automatically work with all Domains / Subdomains."

@bobsta63 

Me.B

**Comment by 5050** [comment]
Correction pushed on github sources for domain and sub-domain modules.
<< It was not possible to create a domain that included "www." inside the name (ie: testwww.com)
now "www." is rejected only when it starts the domain name. >>

**Comment by lottfy** [comment]
@5050 I'm back,What about parked domain is need to apply this fix
Catch latest changes code  and will begin test

**Comment by 5050** [comment]
I apologize a lot to have forgotten parked domains !
