### ISSUE TITLE
Theme Manager tweak

### ISSUE THREAD

**Issue by zHostingSolutions** [zpanel/zpanelx#169]
Hi.

A great idea would be for Theme Manager to be tweaked to where clients, resellers and server admin can choose their own theme for their account if server admin has multiple themes installed instead of themes being global throughout all accounts.

Example:
Server Admin may want to use zpanelx.
Reseller may want to use OrangeJuiceV1.
Client may want to use zSimple.

Of course multiple clients and resellers choose different themes from each other.

Awhile ago, I opened Theme Manager to my client account and changed the theme. Now, although, it didn't change the theme to my server admin account, when I went back to my server admin account and changed the theme, it changed the one for my client account to the one I chosen for server admin.

I was hoping that it wouldn't have been a global change through server admin. I actually thought that as long as I had Theme Manager active in my client account, when I changed the theme in server admin, the theme wouldn't change in my client account unless I went back and changed it.

**Comment by trojanspike** [comment]
This is available. Users that have permission to use the Theme manager can change the theme that only they see.

**Comment by ghost** [comment]
@zHostingSolutions stop posting features request here and use forums to discuss this. This is not helping developers who need to focus here on urgent bugs.

Me.B

**Comment by 5050** [comment]
Already available, I'll close the request.

PLEASE RESERVE THE BUGTRACKER for confirmed and reproductible bugs.

Please expose and discuss about all wishes **on the forum** @ http://forums.zpanelcp.com

**Comment by zHostingSolutions** [comment]
@trojanspike I know that if I open it up to others, they can change their theme. However, what I'm saying it where, even when they change their theme, if server admin changes a theme, it WILL NOT change the theme that others changed.

Right now, it's global based on server admin. What I was talking about for the next version is for it to be a split changer to where server admin won't have a global whenever server admin changes his/her theme.
