### ISSUE TITLE
Module Editor

### ISSUE THREAD

**Issue by zHostingSolutions** [zpanel/zpanelx#170]
A module editor would be great to have as a core module. The object would be:
1. Choose the module from a dropdown menu.
2. From the list of files within that module, click on the file.
3. In the text editor, go to the line that needs to be edited.
4. Save changes.
5. The text editor should also have line numbers to keep track of where you are and make it easier to find the line you're looking for.
6. The text editor should be color-coded.
7. The text editor should be color-coded to let you know when there are open tags, basically, like Dreamweaver.
8. Tabbing should be allowed to be used to line things up within tags.

This way, whenever there are quick fixes, we can edit the module from our control panel. Thanks.

**Comment by ghost** [comment]
Stop posting features requests here and try to discuss them first on forum unless you want to code them and offer a pull here.

BUT any way this would be and extra module not a core module.

@bobsta63 you can close this thread.

Me.B
