### ISSUE TITLE
Text Alert core module

### ISSUE THREAD

**Issue by zHostingSolutions** [zpanel/zpanelx#172]
Hi.

A Text Alert module would be great in order to inform the server admin's phone about the server being down, modules and/or services that stopped working (i.e. ftp, webmail, apache, dns, etc).
1. You enter your phone number(s).
2. When the server is down/offline, a module stops working, or service goes down, a text will be sent to the server admin's phone(s) alerting about the problems.

**Comment by mokiding** [comment]
For "When the server is down/offline, a module stops working, or service goes down, a text will be sent to the server admin's phone(s) alerting about the problems." you will need external server that will send text. Btw it's told you a 1000000 times that THIS ISNT't FEATURE REQUEST THIS IS BUG REPORT FORM ! Are you a idiot or what ? Please go to forum and discuss first.

@bobsta63 it's possble to ban this guy from making issuse requests ?!

**Comment by 5050** [comment]
Hi,
From this page https://help.github.com/articles/blocking-a-user ,  it seems it is not possible to block a user only to open new Issue reports. Blocking a user also disable completely him to
-  open issues
- fork
- send pull requests
- comment on pull requests
- comment on issues
- add or edit wiki pages

By the way:
**@zHostingSolutions** :  **You have been warned many time** to use the forum prior to open an issue for anything other than an effective and replicable bug.

The next time, I will effectively block you.

**Comment by lottfy** [comment]
@zHostingSolutions :We're here only focus to fix bugs,If you need to add new feature code it and share it

**Comment by zHostingSolutions** [comment]
I used to use the forum. However, for the previous bugs.zpanelcp.com, I was told to use it. Now, do we use this, or the forum? I'm mixed up.

**Comment by lottfy** [comment]
Here only to report bugs ,forums share your idea's/Feature's
