### ISSUE TITLE
DNS BIND9 Has issue not reloading

### ISSUE THREAD

**Issue by danielromney** [zpanel/zpanelx#178]
I had a website that consistently showed old DNS information, even after forcing a reload through the module admin. I had to force reload the Bind9 service through SSH. I would take this as a bug that means the Bind9 Module isn't reloading corruptly when told to.

Running Zpanel 10.1.1 on Ubuntu 12.04 LTS on two different server, one on VPS, the other on a physical machine in my house, both had the same issue.

**Comment by ghost** [comment]
Hi,

We would like to check this on support forum before approving it as bug

you are welcome to explain the issue here:

http://forums.zpanelcp.com/

So we check it before validating it for developers and looking for a fix.

Thanks for posting in forum.

Me.B

**Comment by zabounis** [comment]
This issue applies for apache also. It does not reload with the daemon.
Once a new domain created the apache has to be reloaded the hard-way.

**Comment by jacobgelling** [comment]
It works fine for most people so must just be your installs. You'd be best to get support on the forum.
