### ISSUE TITLE
my ip is not working

### ISSUE THREAD

**Issue by 1bitsolutions** [zpanel/zpanelx#182]
My server is a VPS with ubuntu 13.10. the ip is not working, my wrong was install twice zpanel. I saw the hosts file in etc path there were many hosts.

Please help me to solve this problem.

**Comment by stokes84** [comment]
Try the [Support Forum](http://forums.zpanelcp.com/Forum-General-Support-Questions) and please mark this "issue" as closed (the red button near the bottom).

**Comment by ghost** [comment]
@estebing support is on forum please don't disturb dev/bug tracking with support requests here.

M B
