### ISSUE TITLE
Webmail Issue

### ISSUE THREAD

**Issue by zHostingSolutions** [zpanel/zpanelx#184]
Whenever you create a new mailbox, it could take hours, but, MAINLY days before mail is actually sent or received.

It usually take about 5 days, or more, before my mailboxes are able to receive emails when dealing with outside email, like gmail, yahoo, etc. Also, usually, for the first few time; "it varies," but, the email is returned with a 553 error.

**Comment by allebb** [comment]
What OS are you using? - I think you'll find that you must first login to
that mail account (especially on Windows) before it will create the
required data-store directories etc. for that mailbox.

Please try creating a mailbox, logging in to that mailbox using IMAP or
POP3 (or equally using Webmail) and then try sending an external email to
it immediately, that I believe will work just fine!

Let me know :) - If so I'll add some code to do an automatic IMAP login
after the account is created through ZPanel to ensure that the required
directories etc are generated and therefore mailboxes regardless of an
initial login will immediately start accepting mail.

Cheers,
Bobby

**Comment by zHostingSolutions** [comment]
I'm using Ubuntu 12.04LTS.

I use RoundCube to login, the webmail already built into zPanel. Now, it works, sending to, and receiving from external email addresses; I periodically test with my Gmail accounts. Actually, Gmail accounts usually receive emails from the server 99% of the time when I send email after I created a new mailbox. The problem is usually receiving emails from external email.

Now, sometimes with Yahoo emails, they can't even receive emails from my webmail. I usually have to go to my Gmail account and send the email because it was returned back to me after a few hours or 2 days and then ask them to add my server email address to their address book, hoping it'll work. My cousin has Yahoo and it usually takes LOT of time before we're able to steadily correspond. Gmail kind of starts working faster. It's iffy with company email addresses (i.e. user@company.com).

How do I login using IMAP or POP3? Thanks.

**Comment by ghost** [comment]
@zHostingSolutions STOP ASKING for support HERE. This is not the first time.

If you have issues or bug let's discuss them in the forum and we will be happy to log them here once confirmed. 

SO PLEASE USE THE FORUM FOR SUPPORT AND FOR BUG REPORTS FIRST.
