### ISSUE TITLE
Won't install on Ubuntu 14.04

### ISSUE THREAD

**Issue by ingeva** [zpanel/zpanelx#190]
Install script is not updated. Refuses to install on current version of Ubuntu.

**Comment by trojanspike** [comment]
14.04 won't be supported for another while - it's only been released .

**Comment by ingeva** [comment]
On 22. april 2014 11:12, Lee wrote:

> 14.04 won't be supported for another while - it's only been released .

It's very disappointing to find that I need to ryb a two year old 
software
on a new server. So now I need to do everything myself.

inge

## 

Du kan vinne! Uansett!
http://www.youtube.com/watch?v=H8ZuKF3dxCY
For din fremtid:
http://betterglobe.com/12867
Personlige sider:
http://inge.vabekk.no
mob 9050 5331
Min første opptreden som voksen, Mars 2009:
http://youtu.be/VYG-xhcdLOI

**Comment by trojanspike** [comment]
2 years is OK , 4 years + is a good reason for changing to the next stable release.

Problems would come up with 14.04 with software compatibility & working hand in hand , there's no way these could be tested before the release , hense no support for 14.04 " yet ".

You're looking to eat the apple before it's ripe , ;) . Patience

**Comment by allebb** [comment]
You could always weigh up the option of going for a commercial solution
(maybe CPanel or DirectAdmin etc.) that may already support Ubuntu 14.04
(due to the huge resource these commercial companies have and can throw at
testing etc.)

...just an option, otherwise it may be a month before we can officially
support 14.04 given that we do this voluntarily in our own 'free' time..

Regards,
Bobby

**Comment by ingeva** [comment]
On 22. april 2014 12:00, Bobby Allen wrote:

> You could always weigh up the option of going for a commercial solution
> (maybe CPanel or DirectAdmin etc.) that may already support Ubuntu
> 14.04
> (due to the huge resource these commercial companies have and can
> throw at
> testing etc.)
> 
> ...just an option, otherwise it may be a month before we can officially
> support 14.04 given that we do this voluntarily in our own 'free'
> time..

I understand completely, but I wouldn't think that there are too many
differences. I'll set everything up myself, even if a control panel 
would
make things much easier. The only thing I've had trouble with before,
is setting up POP3 email. I guess I can do that too, becvause nothing
is impossible. It just takes more time. :)

I'm an amateur myself, so expensive software is out of the question.

Good luck with your work!

inge

## 

Du kan vinne! Uansett!
http://www.youtube.com/watch?v=H8ZuKF3dxCY
For din fremtid:
http://betterglobe.com/12867
Personlige sider:
http://inge.vabekk.no
mob 9050 5331
Min første opptreden som voksen, Mars 2009:
http://youtu.be/VYG-xhcdLOI

**Comment by allebb** [comment]
Well actually you'd be surprised, a pretty big difference is that Ubuntu
14.04 is that it no longer ships with PHP 5.3 and being such a big part of
ZPanel this obviously needs a lot of attention :)

Cheers,
Bobby

**Comment by ingeva** [comment]
On 22. april 2014 12:52, Bobby Allen wrote:

> Well actually you'd be surprised, a pretty big difference is that
> Ubuntu
> 14.04 is that it no longer ships with PHP 5.3 and being such a big
> part of
> ZPanel this obviously needs a lot of attention :)

I see. Well my own software also requires 5.4 to run properly ... :)
I use my own framework and Joomla! 3.2.

inge

## 

Du kan vinne! Uansett!
http://www.youtube.com/watch?v=H8ZuKF3dxCY
For din fremtid:
http://betterglobe.com/12867
Personlige sider:
http://inge.vabekk.no
mob 9050 5331
Min første opptreden som voksen, Mars 2009:
http://youtu.be/VYG-xhcdLOI

**Comment by trojanspike** [comment]
In my opinion @ingeva , you'd be best sticking with 12.04 & install zpanel for that version.
Then install the PPA for php 5.5 and update & upgrade, apache has some changes too - but in your upgrade and install of php5 you would be given the option to keep the already configed files.

That will keep you stable

**Comment by ingeva** [comment]
On 22. april 2014 13:17, Lee wrote:

> In my opinion @ingeva https://github.com/ingeva , you'd be best
> sticking with 12.04 & install zpanel for that version.
> Then install the PPA for php 5.5 and update & upgrade, apache has
> some changes too - but in your upgrade and install of php5 you would
> be given the option to keep the already configed files.
> 
> That will keep you stable

OK, thanks for the advice!

inge

## 

Du kan vinne! Uansett!
http://www.youtube.com/watch?v=H8ZuKF3dxCY
For din fremtid:
http://betterglobe.com/12867
Personlige sider:
http://inge.vabekk.no
mob 9050 5331
Min første opptreden som voksen, Mars 2009:
http://youtu.be/VYG-xhcdLOI

**Comment by ghost** [comment]
@ingeva Why rushing for 14.04 days after it's released? And 12.04 can be upgraded to 14.04 later.

Our main issue is php/suhosin, we need to check installer over and I think it's a minor issue and should work. But if you upgrade ubuntu you will need likely to apply suhosin AGAIN. @bobsta63 

By the way THIS is installer issue not zpanelX core.

**Comment by zcworld** [comment]
i think from ver 13 + there is no php-suhosin package now, but im looking at the script / testing it
to see IF i can get my head around some of it to get an beta ver of the installer script out to work on ver 14+

but so far 
i got it to half-ass installed ok, without to much work , but there are still BIGGG problems 
but im trying to work on / fix 
but i think its going to take a week or so , due to its like doing my head in :/

**Comment by ingeva** [comment]
On 10. mai 2014 07:59, zcworld wrote:

> i think from ver 13 + there is no php-suhosin package now, but im
> looking at the script / testing it
> to see IF i can get my head around some of it to get an beta ver of
> the installer script out to work on ver 14+
> 
> but so far
> i got it to half-ass installed ok, without to much work , but there
> are still BIGGG problems
> but im trying to work on / fix
> but i think its going to take a week or so , due to its like doing
> my head in :/

I have too many other projects now, so I can wait for this.
I've got 14.04 up and running just fine on my own server
after realising that all apache config-files must end with
".conf".! :)

inge

## 

Du kan vinne! Uansett!
http://www.youtube.com/watch?v=H8ZuKF3dxCY
For din fremtid:
http://betterglobe.com/12867
Personlige sider:
http://inge.vabekk.no
mob 9050 5331
Min første opptreden som voksen, Mars 2009:
http://youtu.be/VYG-xhcdLOI

**Comment by zcworld** [comment]
at the time i got it to work 

have a look here

http://i58.tinypic.com/123vb6p.png
just showing the phpinfo page, 
so people know its not faked

there is about 20 small changed, made, and a package remove ... but more info is on 
http://forums.zpanelcp.com/Thread-Ubuntu-14-0-installer?pid=83028#pid83028
and any updates :)

**Comment by ghost** [comment]
Closing this. We will add 14.04 when it's ready and @zcworld is already helping over this.

**Comment by 5050** [comment]
Sentora 1.0.0 (quite same than zpanel10.1.1) installer is ready and tested for Ubuntu 14.04. Please read
http://docs.sentora.org/index.php?node=22
http://forums.sentora.org/showthread.php?tid=81
https://github.com/sentora/sentora-installers
