### ISSUE TITLE
Site Pro Builder License error

### ISSUE THREAD

**Issue by ghost** [zpanel/zpanelx#194]
Site Pro Builder License error . find attached.

![image](https://cloud.githubusercontent.com/assets/7336235/2764406/4d7ea198-ca13-11e3-9662-fbb9ad9a4600.png)

thanks for support.
IWASSA Co.

**Comment by allebb** [comment]
SiteBuilder is not a 'core' module, you should instead log this error/bug with the module developer (maybe drop them a PM via, the forums: http://forums.zpanelcp.com).

Cheers,
Bobby
