### ISSUE TITLE
Backup Manager 404 Error

### ISSUE THREAD

**Issue by nighodev** [zpanel/zpanelx#197]
Hello,

I try to backup my Zpanel Hostdata with the integrated backup manager, but everytime I get this error: "The requested URL /modules/backupmgr/code/response_normal.php was not found on this server." Using the latest Zpanel Version on Ubuntu 12.04.04.

Regards

Nico

**Comment by ghost** [comment]
@Nico205 for support please use the forums http://forums.zpanelcp.com/

Retrieving backup files had been disabled thru zpanel. But you can do that using FTP.

Not an issue should be closed ( despite we need to cleanup zpanel over this disabled feature).

**Comment by nighodev** [comment]
Ok thx
