### ISSUE TITLE
There's no documentation for default credentials on Vagrant based installs

### ISSUE THREAD

**Issue by joeljuca** [zpanel/zpanelx#208]
Hi.

I just cloned the `zpanelx` repository to check it out and play arround ZPanel. But, there's no information about what is the default user and password the this fresh install. I read the `README.md`, `vagrant_provision.sh`, but there's no information about this.

Where can I find information about this type of installation? I'll contribute with a PR with a properly documentation about how to install and try ZPanel with Vagrant.

**Comment by jacobgelling** [comment]
Try using `zadmin` as username and `vagrant` as password :wink:

**Comment by ghost** [comment]
Use the forums for support thanks

Closing the issue report.

**Comment by joeljuca** [comment]
@Me-Bl actually, it's not a support request, but a development issue. I'm intending to contribute to the project with documentation and code, that's why I opened the issue and asked for the password. There's NO documentation and it's a project problem.

**Comment by ghost** [comment]
/root/passwords.txt usually and believe me you can find help in forums.

And you are welcome.

**Comment by joeljuca** [comment]
Ok, thanks for helping. I'll try to contribute with a Markdown document explaining how to reproduce the ZPanel with a Vagrant based local install.

**Comment by ghost** [comment]
GREAT. Again check our forum and you can beep me if you have any needs. The issue tracker is intended for bug tracking not those kind of discussion ;)
