### ISSUE TITLE
Error in installing script CentOS

### ISSUE THREAD

**Issue by RemiZOffAlex** [zpanel/zpanelx#209]
Сorrection for script https://raw.github.com/zpanel/installers/master/install/CentOS-6_4/10_1_1.sh

--- 10_1_1.sh   2014-05-09 05:20:23.773608155 +0400
+++ 10_1_1.sh    2014-05-09 05:17:05.954407478 +0400
@@ -68,7 +68,7 @@

 # Set custom logging methods so we create a log file in the current working directory.
 logfile=$$.log
-exec >>(tee $logfile)
+exec > >(tee $logfile)
 exec 2>&1

 # ***************************************

**Comment by ghost** [comment]
Aready fixed.

M B
