### ISSUE TITLE
Request, Framework?

### ISSUE THREAD

**Issue by hitech95** [zpanel/zpanelx#213]
Have you ever thought to move to a PHP framework to develop everything in the fastest way?
http://laravel.com/docs/quick
This is quite interesting, I use it recently, but it seems to be really well done.

**Comment by allebb** [comment]
I'm actually a massive fan of Laravel and have written a shed load of web
apps and sites using Laravel, the successor to the current ZPanel is
planned to be written on top of Laravel already! :)

**Comment by MathDerVakker** [comment]
LOL i heard they are busy developing a next gen off Zpanel with Laravel

**Comment by MathDerVakker** [comment]
oops too late.. :P

**Comment by allebb** [comment]
....yep, no rest for the wicked ;) - That is where I've been hiding ;)

**Comment by allebb** [comment]
Will close this 'bug' as this doesn't need to remain 'open' :)

**Comment by hitech95** [comment]
Good!
