### ISSUE TITLE
Zpanel showing menus but body is blank

### ISSUE THREAD

**Issue by ghost** [zpanel/zpanelx#215]
![screen shot 2014-05-21 at 17 02 21](https://cloud.githubusercontent.com/assets/7654884/3036967/e4a465d6-e0b5-11e3-8627-52b9bb15cdeb.png)

Hi there i just install zpanel on a fresh CentOS 6.4 image, it all installed correctly however i am not seeing anything in the body after logging in. 

Please help

**Comment by jacobgelling** [comment]
Please post this on the forums. GitHub issues isn't used for support.

**Comment by ghost** [comment]
USe the forum for support

http://forums.zpanelcp.com/Forum-General-Support-Questions

Closing this

**Comment by brommet87** [comment]
"GitHub issues isn't used for support." Then it is Useless... BTW: The Link to the Forum does not Work... IF you have no Usefull Information then Stop Posting to this Forum @ghost @jacobg830

**Comment by TGates71** [comment]
http://forums.sentora.org
