### ISSUE TITLE
Code page problem after 10.1.0 -> 10.1.1 upgrade

### ISSUE THREAD

**Issue by Ziela** [zpanel/zpanelx#216]
Hello, 
After upgrading ZPanel from 10.1.0 to 10.1.1  Polish translation is not display correctly.
Database has not been change, same database after downgrading is showing translation correctly again ? any patch for this ?

10.1.0 screen (correct)
![zpanel10 1 0](https://cloud.githubusercontent.com/assets/7669236/3053882/a86b67ee-e1b0-11e3-99fa-12aa0ea8333f.PNG)

10.1.1 screen (wrong polish symbols)
![zpanel10 1 1](https://cloud.githubusercontent.com/assets/7669236/3053884/aba9ddb4-e1b0-11e3-8bca-0649d99359e0.PNG)

**Comment by ghost** [comment]
Check with support over this!

M B

**Comment by ghost** [comment]
USE The forum to troubleshoot and try installing ZPX XTS module again as this is realted to translation.

Closing this.

M B
