### ISSUE TITLE
无法保存包数据

### ISSUE THREAD

**Issue by ghostry** [zpanel/zpanelx#219]
你好.我尝试了您的zpanel.他非常不错.但是好像还没有到可以使用的程度,
我安装后先进行语言修改,就遇到了问题,用户设置的语言字段不够长,语言标志没有被完整保存,导致系统崩溃.我手动修复了之后.又发现好多数据库不能储存非英文字符.于是我把每个数据库修改为utf8.
之后我创建一个限制域名数量,邮件数量,ftp账户的包.数据没有被保存下来.
我查看数据表中并没有这些字段.因为我不了解字段怎是什么,所以无法修复此问题.
希望能在这里得到帮助.

**Comment by ghost** [comment]
USE THE FORUM and in ENGLISH!
