### ISSUE TITLE
Feature request: Restart Daemon button

### ISSUE THREAD

**Issue by aqueries** [zpanel/zpanelx#220]
Hi,
just to put it out there. I was wondering if it would be possible to add a button somewhere which restarts the daemon from the webUI rather than having to SSH to the server and restart the daemon from the cli.

Cheers,

Elliot

**Comment by Caffe1neAdd1ct** [comment]
This feature was removed due to people being able to hit the script via the url. Might be possible to require admin logged in session and run through php.

**Comment by MathDerVakker** [comment]
This function is already available in the ZgodX module.
See => http://forums.zpanelcp.com/Thread-ZGodX-module

**Comment by aqueries** [comment]
Oh Excellent. thankyou!
