### ISSUE TITLE
Postfix is using high CPU

### ISSUE THREAD

**Issue by jatinguta** [zpanel/zpanelx#227]
Since couple of hours Postfix is utilizing more CPU of more than 100%.

**Comment by jacobgelling** [comment]
This isn't a ZPanel problem but a server one - please post this on the ZPanel forums if you want support.

**Comment by ghost** [comment]
Fully support the answer above, you have probably not configured correctly config

**Comment by Caffe1neAdd1ct** [comment]
Might be worth checking the maillog / mail.log to see if one of your mail accounts has been compromised, that would produce a fair amount of load... other than that make sure nobody on your server is sending out mass mails.

**Comment by jatinguta** [comment]
Yes, Even I suspects some kind of spam mailing from my VPS.

I am getting lots of bounce back mail
