### ISSUE TITLE
Adding Sub Domain DOES NOT create DNS Record!

### ISSUE THREAD

**Issue by poppabear8883** [zpanel/zpanelx#240]
When you create a new subdomain, it should create a dns record for that domain automatically.

**Comment by devnix** [comment]
I didn't expect that behavour when I created my first subdomain on ZPanel too, and took me a while to understand it as there is no advice about creating a DNS record too.

I don't see this a critical bug, but it should be seriously considered for an upcoming patch or release! (or, at least, show an alert providing info and instructions)

**Comment by poppabear8883** [comment]
So, there should be an extra step to creating a subdomain? I would assume that creating a subdomain (especially to those that are not familiar with how they work), should be as easy as creating the subdomain, not having to go into the dns manager and adding the dns record for the subdomain. Think about it, if a client creates a subdomain and it never seems to resolve, they would be chasing support around or spending hrs trying to figure out why its not working.

These are ofcourse just my own opinion, I think it should be added.

Thanks for reading.

**Comment by devnix** [comment]
IMHO, it shouldn't be an extra step, and that's what I'm saying on my previous post. But maybe there are some more important bugs that may need a faster fix than this. Of course, at least, the panel should have an alert telling the user to create the DNS record.

**Comment by Ron-e** [comment]
Read this post.. -> http://forums.zpanelcp.com/Thread-Create-DNS-Records-Automatically?pid=46920#pid46920
So if you want this you have to mod it... 
see same thread, you have to test it on the current Zpanel version.

**Comment by poppabear8883** [comment]
Ok, so thats fine ... I just thought that this would be a simple addition to the core functionality of ZPanel .. I will work on a module for it .

Off Topic, How does one become a contributor to the zpanel development ?

**Comment by Caffe1neAdd1ct** [comment]
Raise a pull request ... one of the maintainers should accept it if they feel the change would benefit the community / project as a whole.

**Comment by allebb** [comment]
I still believe this should be implemented as a separate 'system module' to marry up the Apache module and the Bind module as I've explained in my forum post that was linked above :)

**Comment by allebb** [comment]
...and just being more specific, I would suggest that it should be a 'system module' that utilising a 'hook' from the apache module that is then executed when new vhosts are created; this in turn should then create the DNS record as required.

**Comment by allebb** [comment]
Closing issue as per my advise above.
