### ISSUE TITLE
Nginx + php-fpm + OPCache

### ISSUE THREAD

**Issue by iberflow** [zpanel/zpanelx#241]
For most of my projects, I've switched from Apache + mod_php to Nginx + php-fpm because of it's performance. And the performance gain is truly visible, reduced CPU+RAM, higher concurrent requests/second for high load apps.

The Zend OPCache module that comes by default in PHP5.5 should also be enabled, it reduces page load time by around 30%.

Maybe someone would like to join me in building a mod for Nginx?

**Comment by allebb** [comment]
Hi Ignas,

I could not agree with you more with regards to LEMP stack performance over
LAMP.... Apache does however provide better support for users to add custom
rewrite rules at runtime as opposed to the current model that nginx
supports and although it's do-able it's a lot more work initially, I'd also
be pushing custom user-specific FPM pools for performance and security
reasons.

I'd be really happy to see a module for Nginx + FPM in ZPanelX/Sentora I
but and like I say, I'll be adding this functionality into Sentora II :)

**Comment by allebb** [comment]
Closing issue as per my advise above, this would not be implemented into the 'core' of ZPanelX but is planned as a core module for Sentora II. More than happy for this to be developed by the community as an 'add-on' module for ZPanel though.

Closing issue in an attempt to keep the 'issues' manageable :)
