### ISSUE TITLE
api.zpanelcp.com 502 error

### ISSUE THREAD

**Issue by aranciaga** [zpanel/zpanelx#246]
Hi there.
api.zpanelcp.com is returning 502 bad gateway error

This is not a real ZPanel bug but, the update system for example can't get the latest version.

Site response: 

502 Bad Gateway
nginx/1.2.9

Regards

**Comment by jacobgelling** [comment]
This has been fixed :+1:

**Comment by IPFaN** [comment]
#Ok, and how to update my zpanel, i run CentOS :) 

My zpanel version is 10.1.1 but is not last from here :S

**Comment by IPFaN** [comment]
Or how to upgrade to Sentora?
What is difference zpanel vs sentora :)

**Comment by jacobgelling** [comment]
If you are running ZPanel 10.1.1 then that is the latest version.

Sentora is a fork of ZPanel though it has not been released yet.

Does your ZPanel still say it is out of date after you queue a full daemon reset and wait 5 minutes?

**Comment by IPFaN** [comment]
Fine, but why u change files in here, how to get this updates from this source hmm, sry my bad english..

**Comment by IPFaN** [comment]
Umm yes my zpanel say, You appear to be running a BETA release, unless you are testing or developing we recommend you download and use the latest stable release (10.0.0).
again

**Comment by IPFaN** [comment]
Congratulations, You are running the most recent version of ZPanel (10.1.1)!
Fixed :D

**Comment by IPFaN** [comment]
Umm any idea how to update to php 5.6.0 thanks :)

**Comment by jacobgelling** [comment]
Currently ZPanel does not officially support PHP 5.6.

Please use the forum for support requests :wink:

**Comment by IPFaN** [comment]
Ok, thanks :) 
I wait for zpanel 10.2.0 :)))
