### ISSUE TITLE
Backup 404 response_normal.php

### ISSUE THREAD

**Issue by GoalTV** [zpanel/zpanelx#248]
Hello.

I have issue on Zpanel when i try lunch backup it says that file response_normal.php is not found.

and i look in ftp and i dont see this file there in /modules/backupmgr/code/response_normal.php

all i have there is
controller.ext.php
dobackup.php
launchbackup.php

I look over google and can't find this file.

**Comment by mokiding** [comment]
https://github.com/zpanel/zpanelx/tree/master/modules/backupmgr/code it's seem's there is no such file ... Try clean reinstal :)

**Comment by GoalTV** [comment]
I tryed many times fresh install even i found my old zpanel don't have it but anyway I moved to diffrent Panel Plesk so issue can be closed but Im not the only one who have this issue

**Comment by 212nath** [comment]
This issue still persists

**Comment by Ron-e** [comment]
Just for your knowledge: Zpanel is dead after the acquisition by Hostwinds and the voluntary staff have started an zPanel clone called Sentora and they have there own forum where they also give zPanel support..

http://sentora.org/
http://forums.sentora.org/

**Comment by Vanessa45** [comment]
Thanks for sharing. But I currently used another backup software i.e CloudBacko pro. Its provides free space on Google Drive, OneDrive, Dropbox into a single large storage. Through CloudBacko pro it is very easy to restore the data. I also try to use Comodo Backup. Keep updating. leaving a link below just check. http://www.cloudbacko.com/
