### ISSUE TITLE
Forum down?

### ISSUE THREAD

**Issue by TVH7** [zpanel/zpanelx#252]
Is the zpanel forum down or something?? Whatsup I cant read any of the posts it just headers me back to the homepage??

I also have an problem with an white screen after login after I setup ssl. Now I've disabled it and it still gives me a white screen after login!

**Comment by Ron-e** [comment]
Yes hostwinds (new owner of zpanel) has decided to close the forum.
Thats one of the reasons why all the volunteer support staff and developers have forked Zpanel and started an new forum under an new name Sentora.
Check out sentora.org / forums.sentora.org.

**Comment by TVH7** [comment]
Thanks for the answer!
