### ISSUE TITLE
Postfix Database not correctly set up

### ISSUE THREAD

**Issue by alana314** [zpanel/zpanelx#272]
After installing zpanel, setting up my domains, email accounts and aliases, I saw this error pop up in the logs:
'zpanel_postfix.alias' doesn't exist
fatal: proxy:mysql:/etc/zpanel/configs/postfix/mysql-virtual_alias_maps.cf(0,lock|fold_fix): table lookup problem

Maybe it was because I'd previously tried to setup postfix, but I had to give the 'postfix' @ 'localhost' the proper permissions in mysql to match /etc/zpanel/configs/postfix/mysql-virtual_alias_maps.cf . Then I also had to recreate all of the postfix databases (http://switch.richard5.net/isp-in-a-box-v2/configuring-the-mail-server-components/setting-up-the-database-for-postfix/ ).

After all of this, I deleted the mailboxes and aliases and recreated them and it started working. I think the frontend should throw an error if it's unable to access the mysql tables.

Thanks for a great program though, this worked after my manual postfix and postfix admin installs failed.

**Comment by Ron-e** [comment]
Just for your knowledge: Zpanel is dead after the acquisition by Hostwinds and the voluntary staff have started an zPanel fork called Sentora and they have there own forum where they also give zPanel support..

http://sentora.org/
http://forums.sentora.org/

**Comment by drawingfrommemory** [comment]
Ah, thank you!

**Comment by alana314** [comment]
Ah, thank you!
